# Generated by Django 5.0.6 on 2024-06-11 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0016_producyimage_color'),
        ('bepocartBackend', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bepocartAdmin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bepocartBackend.customer')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
