# Generated by Django 5.0.6 on 2024-06-14 08:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0017_size_producyimage_size'),
        ('bepocartBackend', '0007_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coupon_type', models.CharField(default='percentage', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('discount_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bepocartAdmin.category')),
                ('discount_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bepocartAdmin.product')),
            ],
            options={
                'db_table': 'Coupen',
            },
        ),
    ]
