# Generated by Django 5.0.6 on 2024-06-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0017_size_producyimage_size'),
        ('bepocartBackend', '0008_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bepocartAdmin.subcategory'),
        ),
    ]
