# Generated by Django 5.0.6 on 2024-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0010_alter_coupon_coupon_type_alter_coupon_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='In Active'),
        ),
    ]
