# Generated by Django 5.0.6 on 2024-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0011_alter_coupon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(default='Percentage', max_length=20),
        ),
    ]
