# Generated by Django 5.0.6 on 2024-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0014_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table=None,
        ),
    ]
