# Generated by Django 5.0.6 on 2024-06-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0015_alter_coupon_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='Coupen',
        ),
    ]
