# Generated by Django 5.0.6 on 2024-06-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0016_alter_coupon_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
