# Generated by Django 5.0.6 on 2024-07-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0021_remove_coupon_discount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(default='In Active', max_length=20),
        ),
    ]
