# Generated by Django 5.0.6 on 2024-07-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0023_order_created_time_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
