# Generated by Django 5.0.6 on 2024-07-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0025_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='Pending', null=True),
        ),
    ]
