# Generated by Django 5.0.6 on 2024-07-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0026_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='free_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
