# Generated by Django 5.1 on 2024-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0027_orderitem_free_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='free_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='free_quantity',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_type',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
