# Generated by Django 5.1 on 2024-08-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0028_remove_orderitem_free_quantity_order_free_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='note',
        ),
    ]
