# Generated by Django 5.1 on 2024-08-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0030_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
