# Generated by Django 5.1 on 2024-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0031_address_note_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='note',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
