# Generated by Django 5.1 on 2024-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0032_remove_address_note_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(default='Processing', null=True),
        ),
    ]
