# Generated by Django 5.1 on 2024-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0034_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
