# Generated by Django 5.1 on 2024-09-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0035_order_razorpay_order_id_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
