# Generated by Django 5.1 on 2024-09-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0037_order_razorpay_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
