# Generated by Django 5.1 on 2024-09-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0037_remove_order_razorpay_order_id'),
        ('bepocartBackend', '0039_alter_order_order_id_alter_order_payment_method'),
    ]

    operations = [
    ]
