# Generated by Django 5.1 on 2024-09-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0040_merge_20240903_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
