# Generated by Django 5.1 on 2024-09-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0041_order_razorpay_order_id_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
