# Generated by Django 5.1 on 2024-09-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0047_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_charge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
