# Generated by Django 5.1 on 2024-09-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0050_alter_customer_email'),
        ('bepocartBackend', '0050_alter_customer_phone'),
    ]

    operations = [
    ]
