<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-09-07 07:50
=======
# Generated by Django 5.1 on 2024-09-07 07:50
>>>>>>> eea94d87d580245cefcff01d59ddf7f466578502

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('bepocartBackend', '0051_merge_20240907_0749'),
=======
        ('bepocartBackend', '0051_merge_20240907_1320'),
>>>>>>> eea94d87d580245cefcff01d59ddf7f466578502
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')]),
        ),
    ]
