# Generated by Django 5.0.6 on 2024-09-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0050_alter_customer_phone'),
        ('bepocartBackend', '0052_alter_customer_phone'),
    ]

    operations = [
    ]
