# Generated by Django 5.1 on 2024-10-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartBackend', '0053_address_name'),
        ('bepocartBackend', '0053_merge_20240913_0511'),
    ]

    operations = [
    ]
