# Generated by Django 5.0.6 on 2024-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0007_product_saleprice_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
