# Generated by Django 5.0.6 on 2024-06-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0009_carousal_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
