# Generated by Django 5.0.6 on 2024-06-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0011_offerbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bepocartAdmin.offerbanner'),
        ),
    ]
