# Generated by Django 5.0.6 on 2024-06-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0012_product_offer_banner'),
        ('bepocartBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bepocartBackend.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bepocartAdmin.product')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
