# Generated by Django 5.0.6 on 2024-07-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0020_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.CharField(default='Active', null=True),
        ),
    ]
