# Generated by Django 5.0.6 on 2024-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0024_alter_coinvalue_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvalue',
            name='login_value',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='payment_value',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
