# Generated by Django 5.0.6 on 2024-07-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0025_coinvalue_login_value_coinvalue_payment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvalue',
            name='anniversary_reward',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='birthday_reward',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='first_payment_value',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='referral_point',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='coinvalue',
            name='review_reward',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='coinvalue',
            name='payment_value',
            field=models.FloatField(null=True),
        ),
    ]
