# Generated by Django 5.0.6 on 2024-07-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0029_remove_producyimage_size_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productverient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verients', to='bepocartAdmin.producyimage')),
            ],
            options={
                'db_table': 'Productverient',
            },
        ),
    ]
