# Generated by Django 5.0.6 on 2024-07-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0031_remove_product_stock_productverient_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
