# Generated by Django 5.0.6 on 2024-07-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0035_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='get_value',
            field=models.IntegerField(),
        ),
    ]
