# Generated by Django 5.0.6 on 2024-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0036_alter_offer_get_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='exclude_categories',
            new_name='excluded_offer_category',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='categories',
            new_name='offer_category',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='products',
            new_name='offer_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='coupon_use_limit',
        ),
        migrations.AddField(
            model_name='offer',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='coupon_user_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_approved_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='free_allowed_offers_category', to='bepocartAdmin.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_approved_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='free_allowed_offers_products', to='bepocartAdmin.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_not_allowd_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='free_not_allowed_offers_cxategory', to='bepocartAdmin.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_not_allowd_products',
            field=models.ManyToManyField(blank=True, null=True, related_name='free_not_allowed_offers_products', to='bepocartAdmin.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='coupon_use_order_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='get_value',
            field=models.IntegerField(null=True),
        ),
    ]
