# Generated by Django 5.0.6 on 2024-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0037_rename_exclude_categories_offer_excluded_offer_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_approved_category',
            field=models.ManyToManyField(blank=True, related_name='free_allowed_offers_category', to='bepocartAdmin.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_approved_products',
            field=models.ManyToManyField(blank=True, related_name='free_allowed_offers_products', to='bepocartAdmin.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_not_allowd_category',
            field=models.ManyToManyField(blank=True, related_name='free_not_allowed_offers_cxategory', to='bepocartAdmin.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_not_allowd_products',
            field=models.ManyToManyField(blank=True, related_name='free_not_allowed_offers_products', to='bepocartAdmin.product'),
        ),
    ]
