# Generated by Django 5.0.6 on 2024-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0038_alter_offer_discount_approved_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.CharField(default='Allowd', max_length=200),
        ),
    ]
