# Generated by Django 5.0.6 on 2024-07-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0040_alter_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
