# Generated by Django 5.0.6 on 2024-07-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0041_alter_offer_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offer',
            table='Offer',
        ),
    ]
