# Generated by Django 5.0.6 on 2024-07-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0042_alter_offer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
