# Generated by Django 5.0.6 on 2024-07-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0044_offerschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
