# Generated by Django 5.0.6 on 2024-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0045_alter_offerschedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active status of the offer'),
        ),
    ]
