# Generated by Django 5.0.6 on 2024-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0046_alter_offerschedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerschedule',
            name='get_option',
            field=models.IntegerField(help_text='Option for GET', null=True),
        ),
    ]
