# Generated by Django 5.0.6 on 2024-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0047_alter_offerschedule_get_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerschedule',
            name='end_date',
            field=models.DateTimeField(help_text='End date of the offer'),
        ),
        migrations.AlterField(
            model_name='offerschedule',
            name='start_date',
            field=models.DateTimeField(help_text='Start date of the offer'),
        ),
    ]
