# Generated by Django 5.0.6 on 2024-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0048_alter_offerschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerschedule',
            name='discount_approved_category',
            field=models.ManyToManyField(blank=True, help_text='Categories approved for discount', related_name='approved_offers', to='bepocartAdmin.subcategory'),
        ),
        migrations.AlterField(
            model_name='offerschedule',
            name='discount_not_allowed_category',
            field=models.ManyToManyField(blank=True, help_text='Categories not allowed for discount', related_name='not_allowed_offers', to='bepocartAdmin.subcategory'),
        ),
    ]
