# Generated by Django 5.0.6 on 2024-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0049_alter_offerschedule_discount_approved_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerschedule',
            name='offer_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
