# Generated by Django 5.0.6 on 2024-08-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0050_offerschedule_offer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producyimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('single', 'Single Product'), ('variant', 'Variant Product')], default='single', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('image1', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image2', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image3', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image4', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image5', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='bepocartAdmin.product')),
            ],
            options={
                'db_table': 'ProductColorStock',
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image2', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image3', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image4', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('image5', models.ImageField(blank=True, max_length=200, upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bepocartAdmin.product')),
            ],
            options={
                'db_table': 'ProductVariant',
            },
        ),
        migrations.CreateModel(
            name='ProductVarientSizeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='bepocartAdmin.productvariant')),
            ],
            options={
                'db_table': 'Size',
            },
        ),
        migrations.DeleteModel(
            name='Productverient',
        ),
        migrations.DeleteModel(
            name='ProducyImage',
        ),
    ]
