# Generated by Django 5.0.6 on 2024-08-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0052_category_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offerschedule',
            table=None,
        ),
    ]
