# Generated by Django 5.0.6 on 2024-08-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0053_alter_offerschedule_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offerschedule',
            table='Offer Schedule',
        ),
    ]
