# Generated by Django 5.1 on 2024-08-21 12:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0055_alter_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousal',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carousal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='carousal',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description for the product page', null=True),
        ),
        migrations.AddField(
            model_name='carousal',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords for the product page', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carousal',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title for the product page', max_length=255, null=True),
        ),
    ]
