# Generated by Django 5.1 on 2024-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0056_carousal_alt_text_carousal_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
