# Generated by Django 5.1 on 2024-08-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bepocartAdmin', '0057_carousal_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousal',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='carousal',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='carousal',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='carousal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bepocartAdmin.subcategory'),
        ),
    ]
